- host: 0.0.0.0
  port: 2999
  debug: true
  cors: false
  rateLimit: 1000
  judges:
    earth-core: 192.168.1.47:173
    north-pole: 192.168.1.47:174
    south-pole: 192.168.1.47:175
    ethereal: 192.168.1.47:172
  database:
    address: localhost:5432
    username: alphanecron
    password: necronthedev
    name: arctic
