// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: igloo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JudgeResult_Verdict int32

const (
	JudgeResult_ACCEPTED              JudgeResult_Verdict = 0
	JudgeResult_WRONG_ANSWER          JudgeResult_Verdict = 1
	JudgeResult_TIME_LIMIT_EXCEEDED   JudgeResult_Verdict = 2
	JudgeResult_MEMORY_LIMIT_EXCEEDED JudgeResult_Verdict = 3
	JudgeResult_RUNTIME_ERROR         JudgeResult_Verdict = 4
)

// Enum value maps for JudgeResult_Verdict.
var (
	JudgeResult_Verdict_name = map[int32]string{
		0: "ACCEPTED",
		1: "WRONG_ANSWER",
		2: "TIME_LIMIT_EXCEEDED",
		3: "MEMORY_LIMIT_EXCEEDED",
		4: "RUNTIME_ERROR",
	}
	JudgeResult_Verdict_value = map[string]int32{
		"ACCEPTED":              0,
		"WRONG_ANSWER":          1,
		"TIME_LIMIT_EXCEEDED":   2,
		"MEMORY_LIMIT_EXCEEDED": 3,
		"RUNTIME_ERROR":         4,
	}
)

func (x JudgeResult_Verdict) Enum() *JudgeResult_Verdict {
	p := new(JudgeResult_Verdict)
	*p = x
	return p
}

func (x JudgeResult_Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JudgeResult_Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_igloo_proto_enumTypes[0].Descriptor()
}

func (JudgeResult_Verdict) Type() protoreflect.EnumType {
	return &file_igloo_proto_enumTypes[0]
}

func (x JudgeResult_Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JudgeResult_Verdict.Descriptor instead.
func (JudgeResult_Verdict) EnumDescriptor() ([]byte, []int) {
	return file_igloo_proto_rawDescGZIP(), []int{2, 0}
}

type Constraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mem uint64 `protobuf:"varint,1,opt,name=mem,proto3" json:"mem,omitempty"`
	Cpu uint32 `protobuf:"varint,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
}

func (x *Constraints) Reset() {
	*x = Constraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_igloo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Constraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraints) ProtoMessage() {}

func (x *Constraints) ProtoReflect() protoreflect.Message {
	mi := &file_igloo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraints.ProtoReflect.Descriptor instead.
func (*Constraints) Descriptor() ([]byte, []int) {
	return file_igloo_proto_rawDescGZIP(), []int{0}
}

func (x *Constraints) GetMem() uint64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *Constraints) GetCpu() uint32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constraints *Constraints `protobuf:"bytes,1,opt,name=constraints,proto3" json:"constraints,omitempty"`
	Language    string       `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Buffer      []byte       `protobuf:"bytes,3,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_igloo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_igloo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_igloo_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetConstraints() *Constraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *File) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *File) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type JudgeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestNumber uint32              `protobuf:"varint,1,opt,name=test_number,json=testNumber,proto3" json:"test_number,omitempty"`
	Memory     uint64              `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Duration   float64             `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Verdict    JudgeResult_Verdict `protobuf:"varint,4,opt,name=verdict,proto3,enum=arctic.JudgeResult_Verdict" json:"verdict,omitempty"`
	Point      uint32              `protobuf:"varint,5,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *JudgeResult) Reset() {
	*x = JudgeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_igloo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JudgeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeResult) ProtoMessage() {}

func (x *JudgeResult) ProtoReflect() protoreflect.Message {
	mi := &file_igloo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeResult.ProtoReflect.Descriptor instead.
func (*JudgeResult) Descriptor() ([]byte, []int) {
	return file_igloo_proto_rawDescGZIP(), []int{2}
}

func (x *JudgeResult) GetTestNumber() uint32 {
	if x != nil {
		return x.TestNumber
	}
	return 0
}

func (x *JudgeResult) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *JudgeResult) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *JudgeResult) GetVerdict() JudgeResult_Verdict {
	if x != nil {
		return x.Verdict
	}
	return JudgeResult_ACCEPTED
}

func (x *JudgeResult) GetPoint() uint32 {
	if x != nil {
		return x.Point
	}
	return 0
}

type Specifications struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsLaptop bool    `protobuf:"varint,1,opt,name=is_laptop,json=isLaptop,proto3" json:"is_laptop,omitempty"`
	Os       string  `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Cpu      string  `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem      float64 `protobuf:"fixed64,4,opt,name=mem,proto3" json:"mem,omitempty"`
}

func (x *Specifications) Reset() {
	*x = Specifications{}
	if protoimpl.UnsafeEnabled {
		mi := &file_igloo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specifications) ProtoMessage() {}

func (x *Specifications) ProtoReflect() protoreflect.Message {
	mi := &file_igloo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specifications.ProtoReflect.Descriptor instead.
func (*Specifications) Descriptor() ([]byte, []int) {
	return file_igloo_proto_rawDescGZIP(), []int{3}
}

func (x *Specifications) GetIsLaptop() bool {
	if x != nil {
		return x.IsLaptop
	}
	return false
}

func (x *Specifications) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Specifications) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *Specifications) GetMem() float64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

type IglooHealth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BootTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=boot_timestamp,json=bootTimestamp,proto3" json:"boot_timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Specs         *Specifications        `protobuf:"bytes,3,opt,name=specs,proto3" json:"specs,omitempty"`
}

func (x *IglooHealth) Reset() {
	*x = IglooHealth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_igloo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IglooHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IglooHealth) ProtoMessage() {}

func (x *IglooHealth) ProtoReflect() protoreflect.Message {
	mi := &file_igloo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IglooHealth.ProtoReflect.Descriptor instead.
func (*IglooHealth) Descriptor() ([]byte, []int) {
	return file_igloo_proto_rawDescGZIP(), []int{4}
}

func (x *IglooHealth) GetBootTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.BootTimestamp
	}
	return nil
}

func (x *IglooHealth) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *IglooHealth) GetSpecs() *Specifications {
	if x != nil {
		return x.Specs
	}
	return nil
}

var File_igloo_proto protoreflect.FileDescriptor

var file_igloo_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x67, 0x6c, 0x6f, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61,
	0x72, 0x63, 0x74, 0x69, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x6d, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x63, 0x70, 0x75, 0x22, 0x71, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x35,
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x72, 0x63, 0x74, 0x69, 0x63, 0x2e, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0xa1, 0x02, 0x0a, 0x0b, 0x4a, 0x75,
	0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x73,
	0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x74, 0x65, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1b, 0x2e, 0x61, 0x72, 0x63, 0x74, 0x69, 0x63, 0x2e, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x2e, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x64, 0x69, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x70, 0x0a, 0x07, 0x56,
	0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x57, 0x52, 0x4f, 0x4e, 0x47, 0x5f, 0x41, 0x4e,
	0x53, 0x57, 0x45, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x4c,
	0x49, 0x4d, 0x49, 0x54, 0x5f, 0x45, 0x58, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x19, 0x0a, 0x15, 0x4d, 0x45, 0x4d, 0x4f, 0x52, 0x59, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f,
	0x45, 0x58, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x55,
	0x4e, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x22, 0x61, 0x0a,
	0x0e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x70, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x65, 0x6d,
	0x22, 0x98, 0x01, 0x0a, 0x0b, 0x49, 0x67, 0x6c, 0x6f, 0x6f, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x12, 0x41, 0x0a, 0x0e, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x62, 0x6f, 0x6f, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a,
	0x05, 0x73, 0x70, 0x65, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61,
	0x72, 0x63, 0x74, 0x69, 0x63, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x73, 0x70, 0x65, 0x63, 0x73, 0x32, 0x6c, 0x0a, 0x05, 0x49,
	0x67, 0x6c, 0x6f, 0x6f, 0x12, 0x35, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x61, 0x72, 0x63, 0x74, 0x69, 0x63, 0x2e,
	0x49, 0x67, 0x6c, 0x6f, 0x6f, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x2c, 0x0a, 0x05, 0x4a,
	0x75, 0x64, 0x67, 0x65, 0x12, 0x0c, 0x2e, 0x61, 0x72, 0x63, 0x74, 0x69, 0x63, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x1a, 0x13, 0x2e, 0x61, 0x72, 0x63, 0x74, 0x69, 0x63, 0x2e, 0x4a, 0x75, 0x64, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x30, 0x01, 0x42, 0x11, 0x5a, 0x0f, 0x61, 0x72, 0x63,
	0x74, 0x69, 0x63, 0x2f, 0x69, 0x67, 0x6c, 0x6f, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_igloo_proto_rawDescOnce sync.Once
	file_igloo_proto_rawDescData = file_igloo_proto_rawDesc
)

func file_igloo_proto_rawDescGZIP() []byte {
	file_igloo_proto_rawDescOnce.Do(func() {
		file_igloo_proto_rawDescData = protoimpl.X.CompressGZIP(file_igloo_proto_rawDescData)
	})
	return file_igloo_proto_rawDescData
}

var file_igloo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_igloo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_igloo_proto_goTypes = []interface{}{
	(JudgeResult_Verdict)(0),      // 0: arctic.JudgeResult.Verdict
	(*Constraints)(nil),           // 1: arctic.Constraints
	(*File)(nil),                  // 2: arctic.File
	(*JudgeResult)(nil),           // 3: arctic.JudgeResult
	(*Specifications)(nil),        // 4: arctic.Specifications
	(*IglooHealth)(nil),           // 5: arctic.IglooHealth
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_igloo_proto_depIdxs = []int32{
	1, // 0: arctic.File.constraints:type_name -> arctic.Constraints
	0, // 1: arctic.JudgeResult.verdict:type_name -> arctic.JudgeResult.Verdict
	6, // 2: arctic.IglooHealth.boot_timestamp:type_name -> google.protobuf.Timestamp
	4, // 3: arctic.IglooHealth.specs:type_name -> arctic.Specifications
	7, // 4: arctic.Igloo.Health:input_type -> google.protobuf.Empty
	2, // 5: arctic.Igloo.Judge:input_type -> arctic.File
	5, // 6: arctic.Igloo.Health:output_type -> arctic.IglooHealth
	3, // 7: arctic.Igloo.Judge:output_type -> arctic.JudgeResult
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_igloo_proto_init() }
func file_igloo_proto_init() {
	if File_igloo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_igloo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Constraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_igloo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_igloo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JudgeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_igloo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specifications); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_igloo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IglooHealth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_igloo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_igloo_proto_goTypes,
		DependencyIndexes: file_igloo_proto_depIdxs,
		EnumInfos:         file_igloo_proto_enumTypes,
		MessageInfos:      file_igloo_proto_msgTypes,
	}.Build()
	File_igloo_proto = out.File
	file_igloo_proto_rawDesc = nil
	file_igloo_proto_goTypes = nil
	file_igloo_proto_depIdxs = nil
}
