// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: blizzard.proto

package blizzard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Case struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Id:
	//
	//	*Case_Problem
	//	*Case_Index
	Id isCase_Id `protobuf_oneof:"id"`
}

func (x *Case) Reset() {
	*x = Case{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blizzard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_blizzard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_blizzard_proto_rawDescGZIP(), []int{0}
}

func (m *Case) GetId() isCase_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *Case) GetProblem() string {
	if x, ok := x.GetId().(*Case_Problem); ok {
		return x.Problem
	}
	return ""
}

func (x *Case) GetIndex() uint32 {
	if x, ok := x.GetId().(*Case_Index); ok {
		return x.Index
	}
	return 0
}

type isCase_Id interface {
	isCase_Id()
}

type Case_Problem struct {
	Problem string `protobuf:"bytes,1,opt,name=problem,proto3,oneof"`
}

type Case_Index struct {
	Index uint32 `protobuf:"varint,2,opt,name=index,proto3,oneof"`
}

func (*Case_Problem) isCase_Id() {}

func (*Case_Index) isCase_Id() {}

type CaseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input  []byte `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Output []byte `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *CaseData) Reset() {
	*x = CaseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blizzard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseData) ProtoMessage() {}

func (x *CaseData) ProtoReflect() protoreflect.Message {
	mi := &file_blizzard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseData.ProtoReflect.Descriptor instead.
func (*CaseData) Descriptor() ([]byte, []int) {
	return file_blizzard_proto_rawDescGZIP(), []int{1}
}

func (x *CaseData) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CaseData) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_blizzard_proto protoreflect.FileDescriptor

var file_blizzard_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x6c, 0x69, 0x7a, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x6c, 0x69, 0x7a, 0x7a, 0x61, 0x72, 0x64, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x08, 0x43, 0x61, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x32, 0x81, 0x01, 0x0a, 0x08, 0x42, 0x6c, 0x69, 0x7a, 0x7a, 0x61, 0x72, 0x64,
	0x12, 0x38, 0x0a, 0x0e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x65, 0x73, 0x74, 0x43, 0x61, 0x73,
	0x65, 0x73, 0x12, 0x0e, 0x2e, 0x62, 0x6c, 0x69, 0x7a, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x61,
	0x73, 0x65, 0x1a, 0x12, 0x2e, 0x62, 0x6c, 0x69, 0x7a, 0x7a, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x61,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x05, 0x41, 0x6c,
	0x69, 0x76, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f,
	0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x62, 0x2f, 0x62, 0x6c,
	0x69, 0x7a, 0x7a, 0x61, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blizzard_proto_rawDescOnce sync.Once
	file_blizzard_proto_rawDescData = file_blizzard_proto_rawDesc
)

func file_blizzard_proto_rawDescGZIP() []byte {
	file_blizzard_proto_rawDescOnce.Do(func() {
		file_blizzard_proto_rawDescData = protoimpl.X.CompressGZIP(file_blizzard_proto_rawDescData)
	})
	return file_blizzard_proto_rawDescData
}

var file_blizzard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blizzard_proto_goTypes = []interface{}{
	(*Case)(nil),                 // 0: blizzard.Case
	(*CaseData)(nil),             // 1: blizzard.CaseData
	(*emptypb.Empty)(nil),        // 2: google.protobuf.Empty
	(*wrapperspb.BoolValue)(nil), // 3: google.protobuf.BoolValue
}
var file_blizzard_proto_depIdxs = []int32{
	0, // 0: blizzard.Blizzard.FetchTestCases:input_type -> blizzard.Case
	2, // 1: blizzard.Blizzard.Alive:input_type -> google.protobuf.Empty
	1, // 2: blizzard.Blizzard.FetchTestCases:output_type -> blizzard.CaseData
	3, // 3: blizzard.Blizzard.Alive:output_type -> google.protobuf.BoolValue
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blizzard_proto_init() }
func file_blizzard_proto_init() {
	if File_blizzard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blizzard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Case); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blizzard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_blizzard_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Case_Problem)(nil),
		(*Case_Index)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blizzard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blizzard_proto_goTypes,
		DependencyIndexes: file_blizzard_proto_depIdxs,
		MessageInfos:      file_blizzard_proto_msgTypes,
	}.Build()
	File_blizzard_proto = out.File
	file_blizzard_proto_rawDesc = nil
	file_blizzard_proto_goTypes = nil
	file_blizzard_proto_depIdxs = nil
}
